Repository os-autoinst/openQA, pull requests merged in 2022-03, with the labels that each got.

#4537 openqa-clone-job: Create jobs atomically to avoid dependency problems
  lib/OpenQA/Script/CloneJob.pm
  script/openqa-clone-job
  t/09-job_clone.t
  t/35-script_clone_job.t
  t/api/04-jobs.t
Labels: not-ready

#4323 Update bootstrap and jquery
  assets/assetpack.def
  assets/stylesheets/result_preview.scss
  templates/webapi/step/viewimg.html.ep
Labels: enhancement

#4579 Update to Bootstrap v4.6.1 for real
  assets/stylesheets/dashboard.scss
  assets/stylesheets/openqa.scss
Labels: merge-fast
